### ISSUE TITLE
Step by step instuctions for beginner

### ISSUE THREAD

**Issue by AnnikaW-dev** [AnnikaW-dev/YogaPause#5]
As a beginner, I want to be able to understand the basic yoga poses so that I can start practicing in an easy and safe way.

**Acceptance Criteria**

- [x] Simple text and images showing each position.
- [x] Clear explanations on how to do each position correctly.
 
**Tasks:**

- [x] Add pictures and text to describe the movments and poses.
- [x] Style the text and images so they are ease to se and follow
