### ISSUE TITLE
Short sessions that is good for your posture and recuce stress

### ISSUE THREAD

**Issue by AnnikaW-dev** [AnnikaW-dev/YogaPause#6]
As a busy office worker, I want to be able to do short yoga exercises at my workplace so that I can reduce stress and improve my posture.

**Acceptance Criteria:**

- [x] A library of short sessions (e.g. 5, 10 and 15 minute yoga sessions)
- [x] Ability to filter on different goals, such as stress management, posture or relaxation.
- [x] Easy navigation on page to quickly find what you need

**Tasks:**

- [x] Make cards with a short discription of the yoga session on home page
