### ISSUE TITLE
Have exercises that are adapted to relieve back pain

### ISSUE THREAD

**Issue by AnnikaW-dev** [AnnikaW-dev/YogaPause#7]
**User story:** As a person with back pain, I want to find yoga exercises that are adapted to relieve back pain and improve my flexibility

** Acceptance Criteria:**

- [ ] A specific program for back pain, with exercises to strengthen and stretch the back.
- [ ] Descriptions on how to modify the exercises to suit one's needs and level.
- [ ] Alternative for seated exercises if it is not possible to stand up.

**Tasks:**

- [ ] Have seated exercises if 
- [ ] All exercises must be able to be done even if you are in pain
