### ISSUE TITLE
suitable for small spaces and easy to learn and navigate

### ISSUE THREAD

**Issue by AnnikaW-dev** [AnnikaW-dev/YogaPause#8]
**User story:** As a yoga lover, I want to be able to find yoga exercises that are suitable for small spaces. not so into technical things so I want it to be easy to use and learn

**Acceptance Criteria:**

- [x]  no need of  tools
- [x] only take up a small space
- [x] easy to understand and learn

**Tasks:**

- [x] Suitable exercises to small places
- [x] Use well known icons and a good navigationbar
